### ISSUE TITLE
GPU capacity

### ISSUE THREAD

**Issue by YamengGu** [YubiaoYue/MedMamba#13]
Hi,

I tried to train my data using this model. My NVIDIA GPU is 20GB. but the code kept saying the GPU is out of memory. i wonder if there is anyone training this model used which capacity GPU.

**Comment by whaibetter** [comment]
32g GPU is out of memory too;

**Comment by jolexu** [comment]
I have the same problem,and I tried to decrease the batch_size to 8 ,then it works ,but too slow.
